name: Deploy or Destroy DeepSeek Model R1
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_or_destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply (on push to main)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
      
      - name: Terraform Destroy (on workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve
      
      - name: Retrieve Terraform Outputs (on push to main)
        if: github.event_name == 'push'
        id: tf_outputs
        run: |
          echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
          echo "LB_DNS=$(terraform output -raw lb_url)" >> $GITHUB_ENV
      
      - name: Save SSH Private Key
        if: github.event_name == 'push'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/my-key.pem
          chmod 600 ~/.ssh/my-key.pem
      
      - name: Install Docker on EC2 (on push to main)
        if: github.event_name == 'push'
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} <<EOF
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl enable docker
          sudo systemctl start docker
          EOF
      
      - name: Deploy DeepSeek Model & WebUI via Docker-Compose (on push to main)
        if: github.event_name == 'push'
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} <<EOF
          git clone https://github.com/your-repo/deepseek.git
          cd deepseek
          docker-compose up -d
          EOF
      
      - name: Validate WebUI is Running (on push to main)
        if: github.event_name == 'push'
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/my-key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} <<EOF
          curl -I http://localhost:8080
          EOF
      
      - name: Validate Load Balancer Access (on push to main)
        if: github.event_name == 'push'
        run: |
          curl -I https://${{ env.LB_DNS }}
      
      - name: Validate Access via Custom Domain (on push to main)
        if: github.event_name == 'push'
        run: |
          curl -I https://deepseek.fozdigitalz.com